# Generated by Django 4.2.1 on 2023-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wine_general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winedata',
            name='country',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='designation',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='points',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='province',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='region_1',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='region_2',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='variety',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='winery',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
