# Generated by Django 4.2.2 on 2023-06-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wine_general', '0003_alter_winedata_points_alter_winedata_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winedata',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='winery',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='region_1',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='region_2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='variety',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='winedata',
            name='province',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
