name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ 3.11 }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ 3.11 }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
        pip install asgiref==3.7.2
        pip install async-generator==1.10
        pip install attrs==23.1.0
        pip install certifi==2023.5.7
        pip install cffi==1.15.1
        pip install chardet==3.0.4
        pip install contourpy==1.0.7
        pip install cycler==0.11.0
        pip install Django==4.2.2
        pip install exceptiongroup==1.1.1
        pip install fonttools==4.39.4
        pip install googletrans==3.0.0
        pip install h11==0.9.0
        pip install h2==3.2.0
        pip install hpack==3.0.0
        pip install hstspreload==2023.1.1
        pip install httpcore==0.9.1
        pip install httpx==0.13.3
        pip install hyperframe==5.2.0
        pip install idna==2.10
        pip install kiwisolver==1.4.4
        pip install matplotlib==3.7.1
        pip install numpy==1.24.3
        pip install outcome==1.2.0
        pip install packaging==23.1
        pip install pandas==2.0.2
        pip install Pillow==9.5.0
        pip install plotly==5.14.1
        pip install pycparser==2.21
        pip install pyparsing==3.0.9
        pip install PySocks==1.7.1
        pip install python-dateutil==2.8.2
        pip install pytz==2023.3
        pip install rfc3986==1.5.0
        pip install seaborn==0.12.2
        pip install selenium==4.10.0
        pip install six==1.16.0
        pip install sniffio==1.3.0
        pip install sortedcontainers==2.4.0
        pip install sqlparse==0.4.4
        pip install tenacity==8.2.2
        pip install trio==0.22.0
        pip install trio-websocket==0.10.2
        pip install tzdata==2023.3
        pip install urllib3==2.0.3
        pip install wsproto==1.2.0
    - name: Run Tests
      run: |
        python manage.py test
