name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install asgiref==3.7.2
        pip install contourpy==1.0.7
        pip install cycler==0.11.0
        pip install Django==4.2
        pip install fonttools==4.39.3
        pip install joblib==1.2.0
        pip install kiwisolver==1.4.4
        pip install matplotlib==3.7.1
        pip install missingno==0.5.2
        pip install numpy==1.24.2
        pip install packaging==23.1
        pip install pandas==2.0.0
        pip install Pillow==9.5.0
        pip install plotly==5.14.1
        pip install pyparsing==3.0.9
        pip install python-dateutil==2.8.2
        pip install pytz==2023.3
        pip install scikit-learn==1.2.2
        pip install scipy==1.10.1
        pip install seaborn==0.12.2
        pip install setuptools==65.5.1
        pip install six==1.16.0
        pip install sqlparse==0.4.3
        pip install tenacity==8.2.2
        pip install threadpoolctl==3.1.0
        pip install tzdata==2023.3
        pip install wheel==0.38.4
    - name: Run Tests
      run: |
        python manage.py test
